<a href="https://colab.research.google.com/github/khaiwalVikrant/ai_ml_practice/blob/decision_and_ensemble/operator_churn_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.style.use("fivethirtyeight")

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_seq_items', None) #For print a long-sequence
pd.set_option('display.max_colwidth', None)
from google.colab import drive

drive.mount('/content/drive')

pd.options.display.float_format = '{:.2f}'.format

import warnings
warnings.filterwarnings('ignore')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [18]:
churn_data = pd.read_csv("/content/drive/MyDrive/ML_Data/telecom_churn_data.csv")

telecom_df_orig = churn_data.copy()

In [15]:
churn_data.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,last_date_of_month_9,arpu_6,arpu_7,arpu_8,arpu_9,onnet_mou_6,onnet_mou_7,onnet_mou_8,onnet_mou_9,offnet_mou_6,offnet_mou_7,offnet_mou_8,offnet_mou_9,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_ic_mou_9,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,roam_og_mou_9,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2t_mou_9,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2m_mou_9,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2f_mou_9,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_t2c_mou_9,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,loc_og_mou_9,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2t_mou_9,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2m_mou_9,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2f_mou_9,std_og_t2c_mou_6,std_og_t2c_mou_7,std_og_t2c_mou_8,std_og_t2c_mou_9,std_og_mou_6,std_og_mou_7,std_og_mou_8,std_og_mou_9,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,isd_og_mou_9,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,spl_og_mou_9,og_others_6,og_others_7,og_others_8,og_others_9,total_og_mou_6,total_og_mou_7,total_og_mou_8,total_og_mou_9,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2t_mou_9,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2m_mou_9,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_t2f_mou_9,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,loc_ic_mou_9,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2t_mou_9,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2m_mou_9,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2f_mou_9,std_ic_t2o_mou_6,std_ic_t2o_mou_7,std_ic_t2o_mou_8,std_ic_t2o_mou_9,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,std_ic_mou_9,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,total_ic_mou_9,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,spl_ic_mou_9,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,isd_ic_mou_9,ic_others_6,ic_others_7,ic_others_8,ic_others_9,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_num_9,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,total_rech_amt_9,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,max_rech_amt_9,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,date_of_last_rech_9,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,last_day_rch_amt_9,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,date_of_last_rech_data_9,total_rech_data_6,total_rech_data_7,total_rech_data_8,total_rech_data_9,max_rech_data_6,max_rech_data_7,max_rech_data_8,max_rech_data_9,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_2g_9,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,count_rech_3g_9,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,av_rech_amt_data_9,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_2g_mb_9,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,vol_3g_mb_9,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_3g_9,arpu_2g_6,arpu_2g_7,arpu_2g_8,arpu_2g_9,night_pck_user_6,night_pck_user_7,night_pck_user_8,night_pck_user_9,monthly_2g_6,monthly_2g_7,monthly_2g_8,monthly_2g_9,sachet_2g_6,sachet_2g_7,sachet_2g_8,sachet_2g_9,monthly_3g_6,monthly_3g_7,monthly_3g_8,monthly_3g_9,sachet_3g_6,sachet_3g_7,sachet_3g_8,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,sep_vbc_3g
0,7000842753,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,197.385,214.816,213.803,21.100,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,NaN,0.00,0.00,0.00,0.00,NaN,NaN,0.16,NaN,NaN,NaN,4.13,NaN,NaN,NaN,1.15,NaN,NaN,NaN,5.44,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.00,NaN,0.00,0.00,5.44,0.00,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,4.0,3.0,2.0,6.0,362.0,252.0,252.0,0.0,252.0,252.0,252.0,0.0,6/21/2014,7/16/2014,8/8/2014,9/28/2014,252.0,252.0,252.0,0.0,6/21/2014,7/16/2014,8/8/2014,NaN,1.0,1.0,1.0,NaN,252.0,252.0,252.0,NaN,0.0,0.0,0.0,NaN,1.0,1.0,1.0,NaN,252.0,252.0,252.0,NaN,30.13,1.32,5.75,0.0,83.57,150.76,109.61,0.00,212.17,212.17,212.17,NaN,212.17,212.17,212.17,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,NaN,968.0,30.4,0.0,101.20,3.58
1,7001865778,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,34.047,355.074,268.321,86.285,24.11,78.68,7.68,18.34,15.74,99.84,304.76,53.76,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,23.88,74.56,7.68,18.34,11.51,75.94,291.86,53.76,0.00,0.00,0.00,0.00,0.0,2.91,0.00,0.00,35.39,150.51,299.54,72.11,0.23,4.11,0.00,0.00,0.00,0.46,0.13,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.23,4.58,0.13,0.00,0.0,0.0,0.0,0.0,4.68,23.43,12.76,0.00,0.00,0.0,0.0,0.0,40.31,178.53,312.44,72.11,1.61,29.91,29.23,116.09,17.48,65.38,375.58,56.93,0.00,8.93,3.61,0.00,19.09,104.23,408.43,173.03,0.00,0.00,2.35,0.00,5.90,0.00,12.49,15.01,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,5.90,0.00,14.84,15.01,26.83,104.23,423.28,188.04,0.00,0.0,0.0,0.00,1.83,0.00,0.0,0.00,0.00,0.00,0.0,0.00,4.0,9.0,11.0,5.0,74.0,384.0,283.0,121.0,44.0,154.0,65.0,50.0,6/29/2014,7/31/2014,8/28/2014,9/30/2014,44.0,23.0,30.0,0.0,NaN,7/25/2014,8/10/2014,NaN,NaN,1.0,2.0,NaN,NaN,154.0,25.0,NaN,NaN,1.0,2.0,NaN,NaN,0.0,0.0,NaN,NaN,154.0,50.0,NaN,0.00,108.07,365.47,0.0,0.00,0.00,0.00,0.00,NaN,0.00,0.00,NaN,NaN,28.61,7.60,NaN,NaN,0.0,0.0,NaN,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,1.0,NaN,1006.0,0.0,0.0,0.00,0.00
2,7001625959,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,167.690,189.058,210.226,290.714,11.54,55.24,37.26,74.81,143.33,220.59,208.36,118.91,0.0,0.00,0.00,38.49,0.0,0.00,0.00,70.94,7.19,28.74,13.58,14.39,29.34,16.86,38.46,28.16,24.11,21.79,15.61,22.24,0.0,135.54,45.76,0.48,60.66,67.41,67.66,64.81,4.34,26.49,22.58,8.76,41.81,67.41,75.53,9.28,1.48,14.76,22.83,0.0,0.0,0.0,0.0,0.0,47.64,108.68,120.94,18.04,0.0,0.0,0.0,0.0,46.56,236.84,96.84,42.08,0.45,0.0,0.0,0.0,155.33,412.94,285.46,124.94,115.69,71.11,67.46,148.23,14.38,15.44,38.89,38.98,99.48,122.29,49.63,158.19,229.56,208.86,155.99,345.41,72.41,71.29,28.69,49.44,45.18,177.01,167.09,118.18,21.73,58.34,43.23,3.86,0.0,0.0,0.0,0.0,139.33,306.66,239.03,171.49,370.04,519.53,395.03,517.74,0.21,0.0,0.0,0.45,0.00,0.85,0.0,0.01,0.93,3.14,0.0,0.36,5.0,4.0,2.0,7.0,168.0,315.0,116.0,358.0,86.0,200.0,86.0,100.0,6/17/2014,7/24/2014,8/14/2014,9/29/2014,0.0,200.0,86.0,0.0,NaN,NaN,NaN,9/17/2014,NaN,NaN,NaN,1.0,NaN,NaN,NaN,46.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,46.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,8.42,NaN,NaN,NaN,2.84,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,1.0,1103.0,0.0,0.0,4.17,0.00
3,7001204172,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,221.338,251.102,508.054,389.500,99.91,54.39,310.98,241.71,123.31,109.01,71.68,113.54,0.0,54.86,44.38,0.00,0.0,28.09,39.04,0.00,73.68,34.81,10.61,15.49,107.43,83.21,22.46,65.46,1.91,0.65,4.91,2.06,0.0,0.00,0.00,0.00,183.03,118.68,37.99,83.03,26.23,14.89,289.58,226.21,2.99,1.73,6.53,9.99,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,29.23,16.63,296.11,236.21,0.0,0.0,0.0,0.0,10.96,0.00,18.09,43.29,0.00,0.0,0.0,0.0,223.23,135.31,352.21,362.54,62.08,19.98,8.04,41.73,113.96,64.51,20.28,52.86,57.43,27.09,19.84,65.59,233.48,111.59,48.18,160.19,43.48,66.44,0.00,129.84,1.33,38.56,4.94,13.98,1.18,0.00,0.00,0.00,0.0,0.0,0.0,0.0,45.99,105.01,4.94,143.83,280.08,216.61,53.13,305.38,0.59,0.0,0.0,0.55,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.80,10.0,11.0,18.0,14.0,230.0,310.0,601.0,410.0,60.0,50.0,50.0,50.0,6/28/2014,7/31/2014,8/31/2014,9/30/2014,30.0,50.0,50.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2491.0,0.0,0.0,0.00,0.00
4,7000142493,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,261.636,309.876,238.174,163.426,50.31,149.44,83.89,58.78,76.96,91.88,124.26,45.81,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,50.31,149.44,83.89,58.78,67.64,91.88,124.26,37.89,0.00,0.00,0.00,1.93,0.0,0.00,0.00,0.00,117.96,241.33,208.16,98.61,0.00,0.00,0.00,0.00,9.31,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,9.31,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,5.98,0.00,0.0,0.0,0.0,127.28,241.33,208.16,104.59,105.68,88.49,233.81,154.56,106.84,109.54,104.13,48.24,1.50,0.00,0.00,0.00,214.03,198.04,337.94,202.81,0.00,0.00,0.86,2.31,1.93,0.25,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,1.93,0.25,0.86,2.31,216.44,198.29,338.81,205.31,0.00,0.0,0.0,0.18,0.00,0.00,0.0,0.00,0.48,0.00,0.0,0.00,5.0,6.0,3.0,4.0,196.0,350.0,287.0,200.0,56.0,110.0,110.0,50.0,6/26/2014,7/28/2014,8/9/2014,9/28/2014,50.0,110.0,110.0,50.0,6/4/2014,NaN,NaN,NaN,1.0,NaN,NaN,NaN,56.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,56.0,NaN,NaN,NaN,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,1526.0,0.0,0.0,0.00,0.00

In [19]:
churn_data.shape

(99999, 226)

In [20]:
churn_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Columns: 226 entries, mobile_number to sep_vbc_3g
dtypes: float64(179), int64(35), object(12)
memory usage: 172.4+ MB

In [34]:
def null_percentage_data(data):
    df = data.copy()
    missing = pd.DataFrame(100*df.isnull().sum()/len(df.index))
    missing.rename(columns={0:'Null_Percentage'}, inplace=True)
    missing = pd.DataFrame(missing.Null_Percentage).sort_values(by='Null_Percentage',ascending=False)
    return missing

In [26]:
churn_data.describe()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,arpu_6,arpu_7,arpu_8,arpu_9,onnet_mou_6,onnet_mou_7,onnet_mou_8,onnet_mou_9,offnet_mou_6,offnet_mou_7,offnet_mou_8,offnet_mou_9,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_ic_mou_9,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,roam_og_mou_9,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2t_mou_9,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2m_mou_9,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2f_mou_9,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_t2c_mou_9,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,loc_og_mou_9,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2t_mou_9,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2m_mou_9,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2f_mou_9,std_og_t2c_mou_6,std_og_t2c_mou_7,std_og_t2c_mou_8,std_og_t2c_mou_9,std_og_mou_6,std_og_mou_7,std_og_mou_8,std_og_mou_9,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,isd_og_mou_9,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,spl_og_mou_9,og_others_6,og_others_7,og_others_8,og_others_9,total_og_mou_6,total_og_mou_7,total_og_mou_8,total_og_mou_9,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2t_mou_9,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2m_mou_9,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_t2f_mou_9,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,loc_ic_mou_9,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2t_mou_9,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2m_mou_9,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2f_mou_9,std_ic_t2o_mou_6,std_ic_t2o_mou_7,std_ic_t2o_mou_8,std_ic_t2o_mou_9,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,std_ic_mou_9,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,total_ic_mou_9,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,spl_ic_mou_9,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,isd_ic_mou_9,ic_others_6,ic_others_7,ic_others_8,ic_others_9,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_num_9,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,total_rech_amt_9,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,max_rech_amt_9,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,last_day_rch_amt_9,total_rech_data_6,total_rech_data_7,total_rech_data_8,total_rech_data_9,max_rech_data_6,max_rech_data_7,max_rech_data_8,max_rech_data_9,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_2g_9,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,count_rech_3g_9,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,av_rech_amt_data_9,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_2g_mb_9,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,vol_3g_mb_9,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_3g_9,arpu_2g_6,arpu_2g_7,arpu_2g_8,arpu_2g_9,night_pck_user_6,night_pck_user_7,night_pck_user_8,night_pck_user_9,monthly_2g_6,monthly_2g_7,monthly_2g_8,monthly_2g_9,sachet_2g_6,sachet_2g_7,sachet_2g_8,sachet_2g_9,monthly_3g_6,monthly_3g_7,monthly_3g_8,monthly_3g_9,sachet_3g_6,sachet_3g_7,sachet_3g_8,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,sep_vbc_3g
count,99999.00,99999.00,98981.00,98981.00,98981.00,99999.00,99999.00,99999.00,99999.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,99999.00,99999.00,99999.00,99999.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,99999.00,99999.00,99999.00,99999.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,96062.00,96140.00,94621.00,92254.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,25153.00,25571.00,26339.00,25922.00,25153.00,25571.00,26339.00,25922.00,25153.00,25571.00,26339.00,25922.00,25153.00,25571.00,26339.00,25922.00,25153.00,25571.00,26339.00,25922.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,25153.00,25571.00,26339.00,25922.00,25153.00,25571.00,26339.00,25922.00,25153.00,25571.00,26339.00,25922.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,25153.00,25571.00,26339.00,25922.00,99999.00,99999.00,99999.00,99999.00,99999.00
mean,7001207270.39,109.00,0.00,0.00,0.00,282.99,278.54,279.15,261.65,132.40,133.67,133.02,130.30,197.94,197.05,196.57,190.34,9.95,7.15,7.29,6.34,13.91,9.82,9.97,8.56,47.10,46.47,45.89,44.58,93.34,91.40,91.76,90.46,3.75,3.79,3.68,3.66,1.12,1.37,1.43,1.23,144.20,141.67,141.33,138.71,79.83,83.30,83.28,82.34,87.30,90.80,89.84,86.28,1.13,1.12,1.07,1.04,0.00,0.00,0.00,0.00,168.26,175.22,174.19,169.66,0.80,0.78,0.79,0.72,3.92,4.98,5.05,4.41,0.45,0.03,0.03,0.05,305.13,310.23,304.12,289.28,47.92,47.99,47.21,46.28,107.48,107.12,108.46,106.16,12.08,12.60,11.75,12.17,167.49,167.72,167.43,164.62,9.58,10.01,9.88,9.43,20.72,21.66,21.18,19.62,2.16,2.22,2.09,2.17,0.00,0.00,0.00,0.00,32.46,33.89,33.15,31.23,200.13,202.85,198.75,189.21,0.06,0.03,0.04,0.16,7.46,8.33,8.44,8.06,0.85,1.01,0.97,1.02,7.56,7.70,7.21,6.89,327.51,322.96,324.16,303.35,104.64,104.75,107.73,101.94,63.16,59.39,62.64,43.90,2.46,2.67,2.65,2.44,126.39,126.73,125.72,124.94,1.86,2.04,2.02,1.78,0.60,0.62,0.64,0.66,192.60,200.98,197.53,192.73,51.90,51.23,50.17,44.72,121.40,129.00,135.41,136.06,89.56,89.38,91.17,100.26,86.40,85.91,86.60,93.71,0.03,0.02,0.02,0.02,0.08,0.08,0.08,0.07,0.39,0.44,0.45,0.39,0.08,0.08,0.08,0.09,0.07,0.08,0.08,0.08,0.91,0.91,0.89,0.86,1219.85,68.17,66.84,60.02,3.30
std,695669.39,0.00,0.00,0.00,0.00,328.44,338.16,344.47,342.00,297.21,308.79,308.95,308.48,316.85,325.86,327.17,319.40,72.83,73.45,68.40,57.14,71.44,58.46,64.71,58.44,150.86,155.32,151.18,148.00,162.78,157.49,156.54,158.68,14.23,14.26,13.27,13.46,5.45,7.53,6.78,5.62,251.75,248.73,245.91,245.93,252.48,263.63,265.49,267.18,255.62,269.35,271.76,261.41,7.98,8.60,7.91,8.26,0.00,0.00,0.00,0.00,389.95,408.92,411.63,405.14,25.77,25.60,25.54,21.31,14.94,20.66,17.86,16.33,4.13,2.16,2.32,3.64,463.42,480.03,478.15,468.98,140.26,145.80,137.24,140.13,171.71,169.42,169.72,165.49,40.14,42.98,39.13,43.84,254.12,256.24,250.03,249.85,54.33,57.41,55.07,53.38,80.79,86.52,83.68,74.91,16.50,16.45,15.81,15.98,0.00,0.00,0.00,0.00,106.28,113.72,110.13,101.98,291.65,298.12,289.32,284.82,0.16,0.16,0.15,0.53,59.72,65.22,63.81,63.51,11.96,12.67,13.28,12.38,7.08,7.07,7.20,7.10,398.02,408.11,416.54,404.59,120.61,124.52,126.90,125.38,97.36,95.92,104.43,90.81,2.79,3.03,3.07,2.52,108.48,109.77,109.44,111.36,2.57,2.77,2.72,2.21,1.27,1.39,1.42,1.41,192.65,196.79,191.30,188.40,213.36,212.30,212.35,198.65,544.25,541.49,558.78,577.39,193.12,195.89,188.18,216.29,172.77,176.38,168.25,171.38,0.16,0.15,0.14,0.13,0.30,0.30,0.30,0.28,1.50,1.64,1.63,1.35,0.36,0.39,0.38,0.38,0.57,0.63,0.66,0.65,0.28,0.29,0.31,0.35,954.73,267.58,271.20,253.94,32.41
min,7000000074.00,109.00,0.00,0.00,0.00,-2258.71,-2014.05,-945.81,-1899.51,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.50,0.50,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-30.82,-26.04,-24.49,-71.09,-35.83,-15.48,-55.83,-45.74,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,180.00,0.00,0.00,0.00,0.00
25%,7000606232.50,109.00,0.00,0.00,0.00,93.41,86.98,84.13,62.69,7.38,6.66,6.46,5.33,34.73,32.19,31.63,27.13,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.66,1.63,1.60,1.36,9.88,10.02,9.81,8.81,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,17.11,17.48,17.11,15.56,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,44.74,43.01,38.58,25.51,2.99,3.23,3.28,3.29,17.29,18.59,18.93,18.56,0.00,0.00,0.00,0.00,30.39,32.46,32.74,32.29,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,38.53,41.19,38.29,32.37,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.00,3.00,3.00,3.00,109.00,100.00,90.00,52.00,30.00,30.00,30.00,28.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,25.00,25.00,25.00,25.00,1.00,1.00,1.00,1.00,0.00,0.00,0.00,0.00,82.00,92.00,87.00,69.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,467.00,0.00,0.00,0.00,0.00
50%,7001204632.00,109.00,0.00,0.00,0.00,197.70,191.64,192.08,176.85,34.31,32.33,32.36,29.84,96.31,91.73,92.14,87.29,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.91,11.61,11.73,11.26,41.03,40.43,40.36,39.12,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,65.11,63.69,63.73,61.84,0.00,0.00,0.00,0.00,3.95,3.63,3.31,2.50,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.64,11.09,10.41,8.41,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,145.14,141.53,138.61,125.46,15.69,15.74,16.03,15.66,56.49,57.08,58.24,56.61,0.88,0.93,0.93,0.96,92.16,92.55,93.83,91.64,0.00,0.00,0.00,0.00,2.03,2.04,2.03,1.74,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.89,5.96,5.88,5.38,114.74,116.34,114.66,105.89,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,6.00,6.00,5.00,5.00,230.00,220.00,225.00,200.00,110.00,110.00,98.00,61.00,30.00,30.00,30.00,0.00,1.00,1.00,1.00,2.00,145.00,145.00,145.00,145.00,1.00,1.00,1.00,1.00,0.00,0.00,0.00,0.00,154.00,154.00,154.00,164.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.48,0.42,0.88,2.60,10.83,8.81,9.27,14.80,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,863.00,0.00,0.00,0.00,0.00
75%,7001812030.50,109.00,0.00,0.00,0.00,371.06,365.34,369.37,353.47,118.74,115.59,115.86,112.13,231.86,226.81,228.26,220.50,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,40.96,39.91,40.11,39.28,110.39,107.56,109.09,106.81,2.08,2.09,2.04,1.94,0.00,0.00,0.00,0.00,168.27,164.38,166.11,162.22,30.81,31.13,30.58,28.23,53.29,54.04,52.49,48.56,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,144.84,150.62,147.94,142.11,0.00,0.00,0.00,0.00,2.43,3.71,3.99,3.23,0.00,0.00,0.00,0.00,372.86,378.57,369.90,353.48,46.84,45.81,46.29,45.18,132.39,130.96,133.93,130.49,8.14,8.28,8.11,8.14,208.08,205.84,207.28,202.74,4.06,4.23,4.08,3.51,15.03,15.74,15.36,14.26,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,26.93,28.31,27.71,25.69,251.67,250.66,248.99,236.32,0.00,0.00,0.00,0.06,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,9.00,10.00,9.00,9.00,437.50,428.00,434.50,415.00,120.00,128.00,144.00,144.00,110.00,110.00,130.00,50.00,3.00,3.00,3.00,3.00,177.00,177.00,179.00,179.00,2.00,2.00,2.00,2.00,1.00,1.00,1.00,1.00,252.00,252.00,252.00,252.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,122.07,119.56,122.07,140.01,122.07,122.07,122.07,140.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,1807.50,0.00,0.00,0.00,0.00
max,7002410905.00,109.00,0.00,0.00,0.00,27731.09,35145.83,33543.62,38805.62,7376.71,8157.78,10752.56,10427.46,8362.36,9667.13,14007.34,10310.76,13724.38,15371.04,13095.36,8464.03,3775.11,2812.04,5337.04,4428.46,6431.33,7400.66,10752.56,10389.24,4729.74,4557.14,4961.33,4429.88,1466.03,1196.43,928.49,927.41,342.86,916.24,502.09,339.84,10643.38,7674.78,11039.91,11099.26,7366.58,8133.66,8014.43,9382.58,8314.76,9284.74,13950.04,10223.43,628.56,544.63,516.91,808.49,0.00,0.00,0.00,0.00,8432.99,10936.73,13980.06,11495.31,5900.66,5490.28,5681.54,4244.53,1023.21,2372.51,1390.88,1635.71,800.89,370.13,394.93,787.79,10674.03,11365.31,14043.06,11517.73,6626.93,9324.66,10696.23,10598.83,4693.86,4455.83,6274.19,5463.78,1872.34,1983.01,2433.06,4318.28,7454.63,9669.91,10830.16,10796.29,5459.56,5800.93,4309.29,3819.83,5647.16,6141.88,5645.86,5689.76,1351.11,1136.08,1394.89,1431.96,0.00,0.00,0.00,0.00,5712.11,6745.76,5957.14,5956.66,7716.14,9699.01,10830.38,10796.59,19.76,21.33,16.86,62.38,6789.41,5289.54,4127.01,5057.74,1362.94,1495.94,2327.51,1005.23,307.00,138.00,196.00,131.00,35190.00,40335.00,45320.00,37235.00,4010.00,4010.00,4449.00,3399.00,4010.00,4010.00,4449.00,3399.00,61.00,54.00,60.00,84.00,1555.00,1555.00,1555.00,1555.00,42.00,48.00,44.00,40.00,29.00,35.00,45.00,49.00,7546.00,4365.00,4076.00,4061.00,10285.90,7873.55,11117.61,8993.95,45735.40,28144.12,30036.06,39221.27,6362.28,4980.90,3716.90,13884.31,6433.76,4809.36,3483.17,3467.17,1.00,1.00,1.00,1.00,4.00,5.00,5.00,4.00,42.00,48.00,44.00,40.00,14.00,16.00,16.00,11.00,29.00,35.00,41.00,49.00,1.00,1.00,1.00,1.00,4337.00,12916.22,9165.60,11166.21,2618.57

In [22]:
null_percentage_data(churn_data)

                          Null_Percentage
date_of_last_rech_data_6        74.846748
total_rech_data_6               74.846748
max_rech_data_6                 74.846748
count_rech_2g_6                 74.846748
av_rech_amt_data_6              74.846748
count_rech_3g_6                 74.846748
arpu_3g_6                       74.846748
arpu_2g_6                       74.846748
fb_user_6                       74.846748
night_pck_user_6                74.846748
arpu_3g_7                       74.428744
av_rech_amt_data_7              74.428744
max_rech_data_7                 74.428744
total_rech_data_7               74.428744
arpu_2g_7                       74.428744
date_of_last_rech_data_7        74.428744
count_rech_2g_7                 74.428744
count_rech_3g_7                 74.428744
fb_user_7                       74.428744
night_pck_user_7                74.428744
arpu_2g_9                       74.077741
arpu_3g_9                       74.077741
date_of_last_rech_data_9        74.077741
night_pck_user_9                74.077741
total_rech_data_9               74.077741
max_rech_data_9                 74.077741
count_rech_3g_9                 74.077741
count_rech_2g_9                 74.077741
fb_user_9                       74.077741
av_rech_amt_data_9              74.077741
total_rech_data_8               73.660737
date_of_last_rech_data_8        73.660737
av_rech_amt_data_8              73.660737
arpu_3g_8                       73.660737
fb_user_8                       73.660737
arpu_2g_8                       73.660737
night_pck_user_8                73.660737
max_rech_data_8                 73.660737
count_rech_3g_8                 73.660737
count_rech_2g_8                 73.660737
loc_ic_t2t_mou_9                 7.745077
spl_og_mou_9                     7.745077
roam_og_mou_9                    7.745077
offnet_mou_9                     7.745077
roam_ic_mou_9                    7.745077
isd_og_mou_9                     7.745077
loc_ic_t2m_mou_9                 7.745077
loc_ic_t2f_mou_9                 7.745077
loc_og_t2f_mou_9                 7.745077
spl_ic_mou_9                     7.745077
std_ic_t2t_mou_9                 7.745077
std_ic_t2f_mou_9                 7.745077
loc_ic_mou_9                     7.745077
std_ic_t2o_mou_9                 7.745077
std_ic_t2m_mou_9                 7.745077
isd_ic_mou_9                     7.745077
ic_others_9                      7.745077
std_ic_mou_9                     7.745077
std_og_t2t_mou_9                 7.745077
std_og_t2m_mou_9                 7.745077
std_og_t2c_mou_9                 7.745077
std_og_t2f_mou_9                 7.745077
loc_og_t2c_mou_9                 7.745077
loc_og_mou_9                     7.745077
loc_og_t2t_mou_9                 7.745077
onnet_mou_9                      7.745077
og_others_9                      7.745077
std_og_mou_9                     7.745077
loc_og_t2m_mou_9                 7.745077
std_og_t2c_mou_8                 5.378054
loc_og_t2f_mou_8                 5.378054
loc_og_t2m_mou_8                 5.378054
loc_ic_mou_8                     5.378054
std_og_t2f_mou_8                 5.378054
std_ic_t2m_mou_8                 5.378054
isd_ic_mou_8                     5.378054
std_ic_t2f_mou_8                 5.378054
std_ic_t2t_mou_8                 5.378054
spl_ic_mou_8                     5.378054
std_ic_t2o_mou_8                 5.378054
ic_others_8                      5.378054
std_ic_mou_8                     5.378054
loc_og_t2c_mou_8                 5.378054
loc_og_mou_8                     5.378054
std_og_t2t_mou_8                 5.378054
roam_ic_mou_8                    5.378054
offnet_mou_8                     5.378054
onnet_mou_8                      5.378054
loc_og_t2t_mou_8                 5.378054
roam_og_mou_8                    5.378054
loc_ic_t2t_mou_8                 5.378054
og_others_8                      5.378054
loc_ic_t2f_mou_8                 5.378054
loc_ic_t2m_mou_8                 5.378054
isd_og_mou_8                     5.378054
std_og_mou_8                     5.378054
std_og_t2m_mou_8                 5.378054
spl_og_mou_8                     5.378054
date_of_last_rech_9              4.760048
std_ic_t2o_mou_6                 3.937039
std_ic_t2f_mou_6                 3.937039
isd_og_mou_6                     3.937039
loc_ic_t2m_mou_6                 3.937039
loc_og_t2f_mou_6                 3.937039
loc_og_t2c_mou_6                 3.937039
std_og_t2f_mou_6                 3.937039
roam_og_mou_6                    3.937039
roam_ic_mou_6                    3.937039
ic_others_6                      3.937039
onnet_mou_6                      3.937039
loc_og_t2t_mou_6                 3.937039
loc_og_t2m_mou_6                 3.937039
loc_og_mou_6                     3.937039
std_og_t2t_mou_6                 3.937039
std_og_t2c_mou_6                 3.937039
std_og_mou_6                     3.937039
std_og_t2m_mou_6                 3.937039
isd_ic_mou_6                     3.937039
std_ic_t2m_mou_6                 3.937039
loc_ic_t2t_mou_6                 3.937039
loc_ic_t2f_mou_6                 3.937039
loc_ic_mou_6                     3.937039
spl_og_mou_6                     3.937039
og_others_6                      3.937039
offnet_mou_6                     3.937039
spl_ic_mou_6                     3.937039
std_ic_mou_6                     3.937039
std_ic_t2t_mou_6                 3.937039
isd_ic_mou_7                     3.859039
std_ic_mou_7                     3.859039
loc_og_t2t_mou_7                 3.859039
onnet_mou_7                      3.859039
roam_og_mou_7                    3.859039
offnet_mou_7                     3.859039
roam_ic_mou_7                    3.859039
std_ic_t2m_mou_7                 3.859039
loc_ic_mou_7                     3.859039
ic_others_7                      3.859039
std_ic_t2f_mou_7                 3.859039
spl_ic_mou_7                     3.859039
std_ic_t2o_mou_7                 3.859039
std_ic_t2t_mou_7                 3.859039
std_og_t2m_mou_7                 3.859039
std_og_t2t_mou_7                 3.859039
std_og_t2f_mou_7                 3.859039
std_og_t2c_mou_7                 3.859039
isd_og_mou_7                     3.859039
loc_og_mou_7                     3.859039
loc_og_t2m_mou_7                 3.859039
loc_og_t2c_mou_7                 3.859039
loc_ic_t2t_mou_7                 3.859039
loc_ic_t2m_mou_7                 3.859039
og_others_7                      3.859039
loc_ic_t2f_mou_7                 3.859039
std_og_mou_7                     3.859039
spl_og_mou_7                     3.859039
loc_og_t2f_mou_7                 3.859039
date_of_last_rech_8              3.622036
date_of_last_rech_7              1.767018
last_date_of_month_9             1.659017
date_of_last_rech_6              1.607016
last_date_of_month_8             1.100011
loc_ic_t2o_mou                   1.018010
std_og_t2o_mou                   1.018010
loc_og_t2o_mou                   1.018010
last_date_of_month_7             0.601006
total_og_mou_7                   0.000000
total_og_mou_9                   0.000000
total_og_mou_8                   0.000000
arpu_6                           0.000000
circle_id                        0.000000
mobile_number                    0.000000
arpu_8                           0.000000
total_og_mou_6                   0.000000
last_date_of_month_6             0.000000
arpu_7                           0.000000
arpu_9                           0.000000
last_day_rch_amt_6               0.000000
total_ic_mou_6                   0.000000
total_ic_mou_9                   0.000000
total_ic_mou_7                   0.000000
total_ic_mou_8                   0.000000
max_rech_amt_9                   0.000000
max_rech_amt_8                   0.000000
max_rech_amt_7                   0.000000
total_rech_num_6                 0.000000
total_rech_num_7                 0.000000
total_rech_num_8                 0.000000
total_rech_num_9                 0.000000
total_rech_amt_6                 0.000000
total_rech_amt_7                 0.000000
total_rech_amt_8                 0.000000
total_rech_amt_9                 0.000000
max_rech_amt_6                   0.000000
last_day_rch_amt_8               0.000000
last_day_rch_amt_7               0.000000
last_day_rch_amt_9               0.000000
vol_2g_mb_6                      0.000000
vol_2g_mb_7                      0.000000
vol_2g_mb_8                      0.000000
vol_2g_mb_9                      0.000000
vol_3g_mb_6                      0.000000
vol_3g_mb_8                      0.000000
vol_3g_mb_7                      0.000000
vol_3g_mb_9                      0.000000
sachet_2g_6                      0.000000
monthly_2g_7                     0.000000
monthly_2g_8                     0.000000
monthly_2g_9                     0.000000
monthly_2g_6                     0.000000
monthly_3g_6                     0.000000
sachet_2g_9                      0.000000
sachet_2g_8                      0.000000
sachet_2g_7                      0.000000
sachet_3g_6                      0.000000
monthly_3g_7                     0.000000
monthly_3g_9                     0.000000
monthly_3g_8                     0.000000
sachet_3g_9                      0.000000
sachet_3g_8                      0.000000
sachet_3g_7                      0.000000
aon                              0.000000
aug_vbc_3g                       0.000000
jul_vbc_3g                       0.000000
jun_vbc_3g                       0.000000
sep_vbc_3g                       0.000000

In [27]:
churn_data = churn_data.rename(columns= lambda x: x.strip(), inplace=False)

In [28]:
churn_data = churn_data.drop_duplicates()

In churn prediction, we are given that there are three phases of customer lifecycle :


1.   The **good** phase [Month 6 & 7]: First two months
2.   The **action** phase [Month 8]: Third month
3.   The **churn** phase [Month 9]: Fourth Month

In [32]:
# Filter both reacharge amount and recharge data
recharge_data_cols = churn_data.columns[churn_data.columns.str.contains("rech_amt|rech_data", regex=True)]
print(recharge_data_cols)

Index(['total_rech_amt_6', 'total_rech_amt_7', 'total_rech_amt_8',
       'total_rech_amt_9', 'max_rech_amt_6', 'max_rech_amt_7',
       'max_rech_amt_8', 'max_rech_amt_9', 'date_of_last_rech_data_6',
       'date_of_last_rech_data_7', 'date_of_last_rech_data_8',
       'date_of_last_rech_data_9', 'total_rech_data_6', 'total_rech_data_7',
       'total_rech_data_8', 'total_rech_data_9', 'max_rech_data_6',
       'max_rech_data_7', 'max_rech_data_8', 'max_rech_data_9',
       'av_rech_amt_data_6', 'av_rech_amt_data_7', 'av_rech_amt_data_8',
       'av_rech_amt_data_9'],
      dtype='object')

Observation: The above mentioned columns correspond to **rech_amt** and **rech_data** features across months 6, 7 and 8 respectively:
- Total recharge amount (calling)
- Maximum recharge amount (calling)
- Last day recharge amount
- Last date of Recharging the data
- Total recharge for data
- Maximum recharge for data
- Average recharge amount for data

In [35]:
recharge_and_data_df = churn_data[recharge_data_cols]
# recharge_and_data_df.columns
null_percentage_data(recharge_and_data_df)

                          Null_Percentage
max_rech_data_6                     74.85
av_rech_amt_data_6                  74.85
total_rech_data_6                   74.85
date_of_last_rech_data_6            74.85
date_of_last_rech_data_7            74.43
total_rech_data_7                   74.43
av_rech_amt_data_7                  74.43
max_rech_data_7                     74.43
av_rech_amt_data_9                  74.08
max_rech_data_9                     74.08
date_of_last_rech_data_9            74.08
total_rech_data_9                   74.08
total_rech_data_8                   73.66
date_of_last_rech_data_8            73.66
max_rech_data_8                     73.66
av_rech_amt_data_8                  73.66
max_rech_amt_9                       0.00
max_rech_amt_8                       0.00
max_rech_amt_7                       0.00
max_rech_amt_6                       0.00
total_rech_amt_9                     0.00
total_rech_amt_8                     0.00
total_rech_amt_7                     0.00
total_rech_amt_6                     0.00

In [36]:
recharge_and_data_df.describe()

,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,total_rech_amt_9,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,max_rech_amt_9,total_rech_data_6,total_rech_data_7,total_rech_data_8,total_rech_data_9,max_rech_data_6,max_rech_data_7,max_rech_data_8,max_rech_data_9,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,av_rech_amt_data_9
count,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,99999.00,25153.00,25571.00,26339.00,25922.00,25153.00,25571.00,26339.00,25922.00,25153.00,25571.00,26339.00,25922.00
mean,327.51,322.96,324.16,303.35,104.64,104.75,107.73,101.94,2.46,2.67,2.65,2.44,126.39,126.73,125.72,124.94,192.60,200.98,197.53,192.73
std,398.02,408.11,416.54,404.59,120.61,124.52,126.90,125.38,2.79,3.03,3.07,2.52,108.48,109.77,109.44,111.36,192.65,196.79,191.30,188.40
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.50,0.50,1.00
25%,109.00,100.00,90.00,52.00,30.00,30.00,30.00,28.00,1.00,1.00,1.00,1.00,25.00,25.00,25.00,25.00,82.00,92.00,87.00,69.00
50%,230.00,220.00,225.00,200.00,110.00,110.00,98.00,61.00,1.00,1.00,1.00,2.00,145.00,145.00,145.00,145.00,154.00,154.00,154.00,164.00
75%,437.50,428.00,434.50,415.00,120.00,128.00,144.00,144.00,3.00,3.00,3.00,3.00,177.00,177.00,179.00,179.00,252.00,252.00,252.00,252.00
max,35190.00,40335.00,45320.00,37235.00,4010.00,4010.00,4449.00,3399.00,61.00,54.00,60.00,84.00,1555.00,1555.00,1555.00,1555.00,7546.00,4365.00,4076.00,4061.00

In [37]:
##Imputation of 'av_rech_amt_data_* and total_rech_data_*' column NaNs with 0 (for all the months 6, 7, 8 and 9 respectively)

churn_data['av_rech_amt_data_6']= churn_data['av_rech_amt_data_6'].fillna(0)
churn_data['av_rech_amt_data_7']= churn_data['av_rech_amt_data_7'].fillna(0)
churn_data['av_rech_amt_data_8']= churn_data['av_rech_amt_data_8'].fillna(0)
churn_data['av_rech_amt_data_9']= churn_data['av_rech_amt_data_9'].fillna(0)

churn_data['total_rech_data_6']= churn_data['total_rech_data_6'].fillna(0)
churn_data['total_rech_data_7']= churn_data['total_rech_data_7'].fillna(0)
churn_data['total_rech_data_8']= churn_data['total_rech_data_8'].fillna(0)
churn_data['total_rech_data_9']= churn_data['total_rech_data_9'].fillna(0)

In [38]:
##Deriving features to subset the high-value customers.

##Calculating total data recharge amt for all the months 6, 7, 8 and 9 respectively.
churn_data['total_rech_data_amt_6'] = (churn_data['av_rech_amt_data_6'] * churn_data['total_rech_data_6'])
churn_data['total_rech_data_amt_7'] = (churn_data['av_rech_amt_data_7'] * churn_data['total_rech_data_7'])
churn_data['total_rech_data_amt_8'] = (churn_data['av_rech_amt_data_8'] * churn_data['total_rech_data_8'])
churn_data['total_rech_data_amt_9'] = (churn_data['av_rech_amt_data_9'] * churn_data['total_rech_data_9'])

In [39]:
##Calculating the total average recharge for good phase: average of (calling recharge costs + data recharge costs) for month (6)
##and (7). Note: Good phase: month (6) and (7)

churn_data['avg_total_rech_plus_data_amt_6_7'] = (churn_data['total_rech_data_amt_6'] + churn_data['total_rech_amt_6']+
                                                  churn_data['total_rech_data_amt_7'] + churn_data['total_rech_amt_7'])/2

**Filter High-Value customers**

Criteria for filtering High-Value Customers:
High-valued customers are those customers who have recharged with an amount more than or equal to X, where X is the **70th percentile** of the average recharge amount in the first two months (the good phase)

Creating a variable **avg_total_rech_plus_data_amt_6_7_70per** to filter high-value customers.

In [41]:
avg_total_rech_plus_data_amt_6_7_70per =  churn_data['avg_total_rech_plus_data_amt_6_7'].quantile(0.7)
print(avg_total_rech_plus_data_amt_6_7_70per)

478.0

In [42]:
highvalue_customer = churn_data.loc[(churn_data.avg_total_rech_plus_data_amt_6_7 > avg_total_rech_plus_data_amt_6_7_70per)]
highvalue_customer.shape

(29953, 231)

In [43]:
#Tagging churners (churn=1, else 0) based on the fourth month(i.e. month of September(9)) and removing attributes corresponding to the churn phase.

churn_phase_cols = ['total_og_mou_9','total_ic_mou_9', 'vol_2g_mb_9', 'vol_3g_mb_9']

churn_phase_cols_df = churn_data[churn_phase_cols]
null_percentage_data(churn_phase_cols_df)

                Null_Percentage
total_og_mou_9             0.00
total_ic_mou_9             0.00
vol_2g_mb_9                0.00
vol_3g_mb_9                0.00

In [45]:
highvalue_customer['total_usage_col_9'] = (churn_data['total_og_mou_9'] + churn_data['total_ic_mou_9'] +
                                   churn_data['vol_2g_mb_9'] + churn_data['vol_3g_mb_9'])

In [46]:
highvalue_customer['churn'] = np.where(highvalue_customer['total_usage_col_9']== 0, 1, 0)

In [47]:
print("Churn data")
highvalue_customer['churn'].value_counts()

Churn data

churn
0    27520
1     2433
Name: count, dtype: int64

In [48]:
print("Churner (%)")
round(100*highvalue_customer['churn'].value_counts()/len(highvalue_customer.index),3)

Churner (%)

churn
0   91.88
1    8.12
Name: count, dtype: float64

In [49]:
#Churn Rate
churn_rate = round(100*highvalue_customer['churn'].sum()/len(highvalue_customer.index),3)
print('Churn Rate(%):',churn_rate)
print("High-Valued Customers Dataset shape: ",highvalue_customer.shape)

Churn Rate(%): 8.123
High-Valued Customers Dataset shape:  (29953, 233)

In [50]:
attributes_9 = list(highvalue_customer.columns[highvalue_customer.columns.str.contains('_9')])

In [51]:
attributes_9.append('sep_vbc_3g')
highvalue_customer.drop(attributes_9, axis=1, inplace=True)
highvalue_customer.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,arpu_8,onnet_mou_6,onnet_mou_7,onnet_mou_8,offnet_mou_6,offnet_mou_7,offnet_mou_8,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2c_mou_6,std_og_t2c_mou_7,std_og_t2c_mou_8,std_og_mou_6,std_og_mou_7,std_og_mou_8,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,og_others_6,og_others_7,og_others_8,total_og_mou_6,total_og_mou_7,total_og_mou_8,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2o_mou_6,std_ic_t2o_mou_7,std_ic_t2o_mou_8,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,ic_others_6,ic_others_7,ic_others_8,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,total_rech_data_6,total_rech_data_7,total_rech_data_8,max_rech_data_6,max_rech_data_7,max_rech_data_8,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_2g_6,arpu_2g_7,arpu_2g_8,night_pck_user_6,night_pck_user_7,night_pck_user_8,monthly_2g_6,monthly_2g_7,monthly_2g_8,sachet_2g_6,sachet_2g_7,sachet_2g_8,monthly_3g_6,monthly_3g_7,monthly_3g_8,sachet_3g_6,sachet_3g_7,sachet_3g_8,fb_user_6,fb_user_7,fb_user_8,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,total_rech_data_amt_6,total_rech_data_amt_7,total_rech_data_amt_8,avg_total_rech_plus_data_amt_6_7,churn
0,7000842753,109,0.00,0.00,0.00,6/30/2014,7/31/2014,8/31/2014,197.38,214.82,213.80,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,0.00,0.00,0.00,NaN,NaN,0.16,NaN,NaN,4.13,NaN,NaN,1.15,NaN,NaN,5.44,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,0.00,0.00,5.44,NaN,NaN,0.00,NaN,NaN,0.00,NaN,NaN,0.00,4,3,2,362,252,252,252,252,252,6/21/2014,7/16/2014,8/8/2014,252,252,252,6/21/2014,7/16/2014,8/8/2014,1.00,1.00,1.00,252.00,252.00,252.00,0.00,0.00,0.00,1.00,1.00,1.00,252.00,252.00,252.00,30.13,1.32,5.75,83.57,150.76,109.61,212.17,212.17,212.17,212.17,212.17,212.17,0.00,0.00,0.00,0,0,0,0,0,0,1,1,1,0,0,0,1.00,1.00,1.00,968,30.40,0.00,101.20,252.00,252.00,252.00,559.00,1
7,7000701601,109,0.00,0.00,0.00,6/30/2014,7/31/2014,8/31/2014,1069.18,1349.85,3171.48,57.84,54.68,52.29,453.43,567.16,325.91,16.23,33.49,31.64,23.74,12.59,38.06,51.39,31.38,40.28,308.63,447.38,162.28,62.13,55.14,53.23,0.00,0.00,0.00,422.16,533.91,255.79,4.30,23.29,12.01,49.89,31.76,49.14,6.66,20.08,16.68,0.00,0.00,0.00,60.86,75.14,77.84,0.00,0.18,10.01,4.50,0.00,6.50,0.00,0.00,0.00,487.53,609.24,350.16,58.14,32.26,27.31,217.56,221.49,121.19,152.16,101.46,39.53,427.88,355.23,188.04,36.89,11.83,30.39,91.44,126.99,141.33,52.19,34.24,22.21,0.00,0.00,0.00,180.54,173.08,193.94,626.46,558.04,428.74,0.21,0.00,0.00,2.06,14.53,31.59,15.74,15.19,15.14,5,5,7,1580,790,3638,1580,790,1580,6/27/2014,7/25/2014,8/26/2014,0,0,779,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,802,57.74,19.38,18.74,0.00,0.00,0.00,1185.00,1
8,7001524846,109,0.00,0.00,0.00,6/30/2014,7/31/2014,8/31/2014,378.72,492.22,137.36,413.69,351.03,35.08,94.66,80.63,136.48,0.00,0.00,0.00,0.00,0.00,0.00,297.13,217.59,12.49,80.96,70.58,50.54,0.00,0.00,0.00,0.00,0.00,7.15,378.09,288.18,63.04,116.56,133.43,22.58,13.69,10.04,75.69,0.00,0.00,0.00,0.00,0.00,0.00,130.26,143.48,98.28,0.00,0.00,0.00,0.00,0.00,10.23,0.00,0.00,0.00,508.36,431.66,171.56,23.84,9.84,0.31,57.58,13.98,15.48,0.00,0.00,0.00,81.43,23.83,15.79,0.00,0.58,0.10,22.43,4.08,0.65,0.00,0.00,0.00,0.00,0.00,0.00,22.43,4.66,0.75,103.86,28.49,16.54,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,19,21,14,437,601,120,90,154,30,6/25/2014,7/31/2014,8/30/2014,50,0,10,NaN,7/31/2014,8/23/2014,0.00,2.00,3.00,NaN,154.00,23.00,NaN,2.00,3.00,NaN,0.00,0.00,0.00,177.00,69.00,0.00,356.00,0.03,0.00,750.95,11.94,NaN,0.00,19.83,NaN,0.00,0.00,NaN,0.00,0.00,0,1,0,0,1,3,0,0,0,0,0,0,NaN,1.00,1.00,315,21.03,910.65,122.16,0.00,354.00,207.00,696.00,0
21,7002124215,109,0.00,0.00,0.00,6/30/2014,7/31/2014,8/31/2014,514.45,597.75,637.76,102.41,132.11,85.14,757.93,896.68,983.39,0.00,0.00,0.00,0.00,0.00,0.00,4.48,6.16,23.34,91.81,87.93,104.81,0.75,0.00,1.58,0.00,0.00,0.00,97.04,94.09,129.74,97.93,125.94,61.79,665.36,808.74,876.99,0.00,0.00,0.00,0.00,0.00,0.00,763.29,934.69,938.79,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,860.34,1028.79,1068.54,2.48,10.19,19.54,118.23,74.63,129.16,4.61,2.84,10.39,125.33,87.68,159.11,14.06,5.98,0.18,67.69,38.23,101.74,0.00,0.00,0.00,0.00,0.00,0.00,81.76,44.21,101.93,207.09,131.89,261.04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,22,26,27,600,680,718,50,50,50,6/30/2014,7/31/2014,8/31/2014,30,20,50,NaN,NaN,NaN,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,720,0.00,0.00,0.00,0.00,0.00,0.00,640.00,0
23,7000887461,109,0.00,0.00,0.00,6/30/2014,7/31/2014,8/31/2014,74.35,193.90,366.97,48.96,50.66,33.58,85.41,89.36,205.89,0.00,0.00,0.00,0.00,0.00,0.00,48.96,50.66,33.58,82.94,83.01,148.56,0.00,0.00,0.00,0.00,0.00,17.71,131.91,133.68,182.14,0.00,0.00,0.00,2.36,6.35,39.61,0.00,0.00,0.00,0.00,0.00,0.00,2.36,6.35,39.61,0.00,0.01,0.00,0.10,0.00,17.71,0.00,0.00,0.00,134.38,140.04,239.48,20.71,61.04,76.64,95.91,113.36,146.84,0.00,0.00,0.71,116.63,174.41,224.21,0.51,0.00,13.38,2.43,14.89,43.91,0.00,0.00,0.00,0.00,0.00,0.00,2.94,14.89,57.29,119.58,222.89,298.33,0.00,0.00,0.00,0.00,28.23,3.74,0.00,5.35,13.06,3,5,4,0,454,439,0,179,179,6/18/2014,7/7/2014,8/24/2014,0,179,0,NaN,7/7/2014,8/6/2014,0.00,2.00,2.00,NaN,179.00,179.00,NaN,0.00,0.00,NaN,2.00,2.00,0.00,356.00,270.00,0.00,0.48,0.01,0.00,599.09,1009.92,NaN,306.57,197.27,NaN,301.78,150.67,NaN,0.00,0.00,0,0,0,0,0,0,0,2,1,0,0,1,NaN,1.00,1.00,604,40.45,51.86,0.00,0.00,712.00,540.00,583.00,0